### ISSUE TITLE
Article on CNN missing

### ISSUE THREAD

**Issue by FelixFrohnertDB** [patrickemonts/zettelkasten#6]
Test Issue: Would it be possible to write article on CNN.

**Comment by AdrianPerezSalinas** [comment]
CNN is Classical Neural Networks?

**Comment by patrickemonts** [comment]
CNN usually stands for Convolutional Neural Network.

**Comment by AdrianPerezSalinas** [comment]
But there is no Neural Network note either

**Comment by patrickemonts** [comment]
Felix just wanted to test how issues work. He has a note on Neural Networks in his branch. It did not make it into the main branch yet: https://github.com/patrickemonts/zettelkasten/blob/fd1ffe13f93f197a9654e68a8128e77cd7b779ac/vault/Neural%20Networks.md
There is an open pull request for it: #5

**Comment by AdrianPerezSalinas** [comment]
aaah I see, sorry
